name: PlatformIO CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'doc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system platformio
      - name: Run Platformio
        run: pio run
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/*/firmware.bin
            .pio/build/*/bootloader.bin
            .pio/build/*/partitions.bin
            ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin
